### PR TITLE
Use FetchContent to retrieve libigl + enables Github Actions.

### PR DESCRIPTION
**Pull request by jdumas**

### CODE REVIEW

**Review by alecjacobson — CHANGES_REQUESTED** [review]
There needs to be a way to point this at an existing installation of libigl. This appears to always download by default with no way of overriding it.

**Comment by jdumas** [comment]
I was wondering about adding a comment about that on the README. You can override the FetchContent to use a local copy of libigl by specifying the CMake variable `FETCHCONTENT_SOURCE_DIR_LIBIGL` when configuring the CMake project.

**Comment by alecjacobson** [comment]
Nice, that's easy. Yes, a note in the README.md is important especially because that variable `FETCHCONTENT_SOURCE_DIR_LIBIGL` doesn't seem to appear anywhere in the CMAKE files.

**Comment by jdumas** [comment]
It is a feature provided by [CMake FetchContent](https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_populate), but it is not obvious for users unfamiliar with FetchContent. I have added an explanation in the README.

**Pull request merged**
