### PR TITLE
Update example to match new Viewer + add libigl as a submodule.

### PR DESCRIPTION
**Pull request by jdumas**
Having libigl as a submodule is useful to make sure the example is always in sync with a working version of libigl.

### CODE REVIEW

**Comment by danielepanozzo** [comment]
This was not done on purpose, to avoid people to have to clone an entire libigl only to set up a new project. I see the problem, but I don't like the submodule solution :)

**Comment by jdumas** [comment]
Well people don't *have* to clone the submodule. If you do `git clone https://github.com/libigl/libigl-example-project.git` without the `--recursive` option it will not clone the submodule. Otherwise we could just keep a file with the hash to the last commit it was tested with ... but well that's basically a submodule =). I don't have any preference on the matter (except that maybe that the usual submodule would be easier to maintain).

**Comment by alecjacobson** [comment]
Agree with Daniele. If we use a sub module then this example is a bit
pointless.

**Comment by jdumas** [comment]
Ok so I've updated the README to include a valid commit number against which the example project was tested (so now the instructions update/init the libigl submodules after the checkout is done).

**Pull request merged**
